### ISSUE TITLE
DevilutionX patches

### ISSUE THREAD

**Issue by AJenbo** [jasperla/openbsd-wip#126]
Hey, what would be required to merge the patches for DevilutionX?

**Comment by rfht** [comment]
What do you mean? Merge https://github.com/jasperla/openbsd-wip/pull/125 into the openbsd-wip repo? Or make patches for upstream? The clang patches need a closer look, and probably some communication with FreeBSD folks to upstream something reasonable.

**Comment by AJenbo** [comment]
Upsream. Thanks for the info :+1:
