### ISSUE TITLE
multimedia/obs-studio: ddb> kernel panic on attaching v4l2 capture device to scene

### ISSUE THREAD

**Issue by n0xa** [jasperla/openbsd-wip#143]
Reproduceable on my ThinkPad X1 Carbon Gen 8 running OpenBSD-CURRENT.
Webcam device:
uvideo0 at uhub0 port 8 configuration 1 interface 0 "Azurewave Integrated Camera" rev 2.01/60.04 addr 2

obs otherwise runs well, and I have successfully streamed to YouTube with it.

Steps to reproduce kernel panic in my environment:
Add a source of "Video Capture Device (v4l2)"
On the dialog, "Create new" is selected by default. Click "Ok"
Camera light turns on. Screen locks up for a few seconds, then I get the text-mode display with a crash.  Last few lines here. Photo of full screen output attached. Dmesg also attached.

kernel: page fault trap, code=0
Stopped at       uvideo_vs_decode_stream_header+0x2c:     movzbl  0(%rsi),%esi
ddb> 

[dmesg.txt](https://github.com/jasperla/openbsd-wip/files/6389330/dmesg.txt)

![20210427_131702](https://user-images.githubusercontent.com/23286114/116352419-bc4f4780-a7ba-11eb-810e-33a577ee90a1.jpg)

**Comment by grayed** [comment]
I'd recommend to send this to bugs@openbsd.org, this is not a port's bug per se.

**Comment by rfht** [comment]
closing this; will need to update obs draft anyway
