### ISSUE TITLE
write access to add jitis-meet ports for eurobsdcon

### ISSUE THREAD

**Issue by epsilon-0** [jasperla/openbsd-wip#151]
I wanted to add a few ports for jitsi meet things that Philipp Buehler is presenting at Eurobsdcon. As this is the standard location for ports not in the tree yet, it might be good to keep them here for public access.

They are currently in my local tree https://github.com/epsilon-0/openbsd-pports/, www/jitsi-meet, net/jitsi-videobridge, net/jicofo.

A bit about me, I maintain a few ports in the openbsd tree, like net/knot and security/vaultwarden, among others. I also dabble a bit with smtpd and ldap stuff.

Cheers!

**Comment by qbit** [comment]
++

**Comment by rfht** [comment]
++

**Comment by epsilon-0** [comment]
Ah forgot about this :D 
We managed to get it in ports, so no worries about this.
