### ISSUE TITLE
games/godot4: Build fails on amd64

### ISSUE THREAD

**Issue by nbonfils** [jasperla/openbsd-wip#165]
I am on OpenBSD -current and when trying to build godot4 I get the following log which ends in an error of the build:
[godot4_build.log](https://github.com/jasperla/openbsd-wip/files/13199871/godot4_build.log)

This seems weird because either this line is not working:
https://github.com/jasperla/openbsd-wip/blob/abcf5567fd136a1c93186e558a2f28caf5964101/games/godot4/Makefile#L55

Or there is a missing `miniupnpc` dependency in the Makefile.

And lastly thank you @omar-polo and @rfht for your recent work on Godot 4 for OpenBSD.
Pinging you, since I believe you probably are the best people to understand that issue.

**Comment by omar-polo** [comment]
@nbonfils the port' makefile was missing some dependencies which I've added in #166.   For packages, we prefer to use the libraries from packages instead of the bundled copies (as a rule of thumb.)  Thomas and I already had the other dependencies installed and that's why we haven't noticed yet.

**Comment by nbonfils** [comment]
Nice, thanks for the fix!
I got the feeling that this might be the case.
I tried compiling with the new makefile and it succeeded.
