### ISSUE TITLE
Question: What is the status of MATE? Is it usable? How stable?

### ISSUE THREAD

**Issue by ynoauun** [jasperla/openbsd-wip#69]
Hi,

I'd like to inquire as to how far off the MATE port is from being usable for everyday life. Should I hold my breath? Does anyone use it daily as is?

Anything in the way of a status update would be greatly appreciated.

Thanks!

**Comment by sizeofvoid** [comment]
Mate is imported in CVS : http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/x11/mate/

**Comment by ynoauun** [comment]
Very nice! I wonder what it will take to get it promoted to a package.

**Comment by ibara** [comment]
They already are.
The following should get you up and running:
```
pkg_add atril caja caja-extensions engrampa eom marco mate-calc mate-control-center mate-desktop mate-icon-theme mate-media mate-menus mate-notification-daemon mate-panel mate-power-manager mate-screensaver mate-session-manager mate-settings-daemon mate-terminal mate-themes mate-utils pluma
```
Yes, I agree it would be nice to have a meta-package so you can just `pkg_add mate` but I'm sure that's on its way once MATE has been up and tested more (and now you can help with that process!).
