### ISSUE TITLE
Basic commands not working

### ISSUE THREAD

**Issue by Astumed** [jasperla/openbsd-wip#77]
Hi, while fetching openbsd-wip in my ports tree? basic commands like 'nano', 'ls' or even 'pkg_add' are now unknown commands, I don't know if this is related with your project but I wanted to let you know because as I said I was installing the tree before shuting down my VM.

**Comment by thfrwn** [comment]
I'm not sure what exactly you did, maybe you messed up your PATH in the process? Hope you didn't run things as root and messed up /usr/bin etc...

Anyway, without you providing details on what exactly you did I can just guess why your commands broke.

Please note that this is a development repository, so you should keep it separate from actual ports or other system directories. I keep this repository in /usr/ports/mystuff, others keep it in /usr/ports/openbsd-wip... Please make sure you look at the (README)[https://github.com/jasperla/openbsd-wip/blob/master/README.md] to understand what this repository is about and how to work with it.

The OpenBSD ports tree is available here:

https://www.openbsd.org/anoncvs.html

Generally try to set it up so you don't need root to fetch or update ports tree, especially if you messed up commands like you described.
How to set it up without needing root is actually better explained in [FAQ 5](https://www.openbsd.org/faq/faq5.html).

**Comment by Astumed** [comment]
Okay, rebooting the machine and changing the PORTSDIR made it work again, cool. And to inform you, the plasma install seems bad, it tries to fetch the packages to a japanese server

**Comment by thfrwn** [comment]
glad you got it fixed
